<?php

// KhelSutra Test Data Safe Cleanup Utility
// Cleans test fixtures generated by automated test suites while preserving all legitimate demo & user data.

if (file_exists(__DIR__ . '/../bootstrap/app.php')) {
    require_once __DIR__ . '/../bootstrap/app.php';
} elseif (file_exists(__DIR__ . '/bootstrap/app.php')) {
    require_once __DIR__ . '/bootstrap/app.php';
}

use App\Services\BaseService;

$pdo = BaseService::getDatabaseConnection();

$isDryRun = in_array('--dry-run', $argv);
echo "====================================================\n";
echo " KhelSutra Test Data Safe Cleanup Utility           \n";
echo " Mode: " . ($isDryRun ? "DRY RUN (preview only)" : "LIVE EXECUTION (safe cleanup)") . "\n";
echo "====================================================\n\n";

// -------------------------------------------------------------
// 1. PRESERVED BASELINE & HUMAN USER DATA SCOPE
// -------------------------------------------------------------

// Tournaments to preserve:
// - #1: Apex Champions League 2026 (Baseline required by /tournaments/1)
// - #28: inter college cricket tournament (User created)
// - #32: Apex Super Cup 2026 Updated (User manual test, soft-deleted)
// - #70: football match (User created)
// - #71: football match (User created)
$preservedTournIds = [1, 28, 32, 70, 71];

// Teams to preserve:
// - #1: Apex Test Strikers Elite (Baseline required by /teams/1)
// - #21: teen titans (User created)
$preservedTeamIds = [1, 21];

// Athletes to preserve:
// - #1: Aarav Patel (Baseline required by /athletes/1)
// - #23: Parth naik (User created)
// - #65: jeet singh (User created)
$preservedAthleteIds = [1, 23, 65];

// Coach Profiles to preserve:
// - #1: Sanjay Bangar (Baseline required by /coaches/1, head coach of Team 1)
// - #14: Sanjay bhai (User created coach, head coach of Team 21)
$preservedCoachProfileIds = [1, 14];

// Employees to preserve:
// - #1: Suresh Raina (Baseline employee)
// - #4: Sanjay Bangar (Employee for Coach Profile 1)
// - #31: Sanjay bhai (Employee for Coach Profile 14)
$preservedEmployeeIds = [1, 4, 31];

// Venues to preserve:
// - #1: Apex Test Arena 806 (Baseline required by /venues/1)
// - #35: Futsal Arena (User created venue in Mapusa)
$preservedVenueIds = [1, 35];

// Training sessions to preserve:
// - #1: Automated Defensive Tactics Session (Baseline required by /training/1)
$preservedTrainingSessionIds = [1];

// Inventory items to preserve:
// - #1: TEST-BALL-199 (Baseline required by /inventory/1)
$preservedInventoryItemIds = [1];

// -------------------------------------------------------------
// 2. AUDIT RECORDS TO REMOVE / REMAP
// -------------------------------------------------------------

$tournIdList = implode(',', $preservedTournIds);
$testTournIds = $pdo->query("SELECT id FROM tournaments WHERE id NOT IN ({$tournIdList})")->fetchAll(PDO::FETCH_COLUMN);
$testTournCount = count($testTournIds);

$fixtureCount = 0;
$matchCount = 0;
$standingsCount = 0;
$tournTeamsCount = 0;
$tournVenuesCount = 0;

if (!empty($testTournIds)) {
    $tIdsStr = implode(',', $testTournIds);
    $fixtureCount = (int)$pdo->query("SELECT COUNT(*) FROM fixtures WHERE tournament_id IN ({$tIdsStr})")->fetchColumn();
    $matchCount = (int)$pdo->query("SELECT COUNT(*) FROM matches WHERE fixture_id IN (SELECT id FROM fixtures WHERE tournament_id IN ({$tIdsStr}))")->fetchColumn();
    $standingsCount = (int)$pdo->query("SELECT COUNT(*) FROM tournament_standings WHERE tournament_id IN ({$tIdsStr})")->fetchColumn();
    $tournTeamsCount = (int)$pdo->query("SELECT COUNT(*) FROM tournament_teams WHERE tournament_id IN ({$tIdsStr})")->fetchColumn();
    $tournVenuesCount = (int)$pdo->query("SELECT COUNT(*) FROM tournament_venues WHERE tournament_id IN ({$tIdsStr})")->fetchColumn();
}

$teamIdList = implode(',', $preservedTeamIds);
$testTeamIds = $pdo->query("SELECT id FROM teams WHERE id NOT IN ({$teamIdList})")->fetchAll(PDO::FETCH_COLUMN);
$testTeamCount = count($testTeamIds);

$teamCoachesCount = 0;
$teamMembersCount = 0;
if (!empty($testTeamIds)) {
    $tmIdsStr = implode(',', $testTeamIds);
    $teamCoachesCount = (int)$pdo->query("SELECT COUNT(*) FROM team_coaches WHERE team_id IN ({$tmIdsStr})")->fetchColumn();
    $teamMembersCount = (int)$pdo->query("SELECT COUNT(*) FROM team_members WHERE team_id IN ({$tmIdsStr})")->fetchColumn();
}

$athIdList = implode(',', $preservedAthleteIds);
$testAthleteIds = $pdo->query("SELECT id FROM athletes WHERE id NOT IN ({$athIdList})")->fetchAll(PDO::FETCH_COLUMN);
$testAthleteCount = count($testAthleteIds);

$guardiansCount = 0;
if (!empty($testAthleteIds)) {
    $aIdsStr = implode(',', $testAthleteIds);
    $guardiansCount = (int)$pdo->query("SELECT COUNT(*) FROM athlete_guardians WHERE athlete_id IN ({$aIdsStr})")->fetchColumn();
}

$cpIdList = implode(',', $preservedCoachProfileIds);
$testCoachProfileCount = (int)$pdo->query("SELECT COUNT(*) FROM coach_profiles WHERE id NOT IN ({$cpIdList})")->fetchColumn();

$empIdList = implode(',', $preservedEmployeeIds);
$testEmployeeCount = (int)$pdo->query("SELECT COUNT(*) FROM employees WHERE id NOT IN ({$empIdList})")->fetchColumn();

$venueIdList = implode(',', $preservedVenueIds);
$testVenueIds = $pdo->query("SELECT id FROM venues WHERE id NOT IN ({$venueIdList})")->fetchAll(PDO::FETCH_COLUMN);
$testVenueCount = count($testVenueIds);

$venueBookingsCount = 0;
$venueFacilitiesCount = 0;
if (!empty($testVenueIds)) {
    $vIdsStr = implode(',', $testVenueIds);
    $venueBookingsCount = (int)$pdo->query("SELECT COUNT(*) FROM venue_bookings WHERE venue_id IN ({$vIdsStr})")->fetchColumn();
    $venueFacilitiesCount = (int)$pdo->query("SELECT COUNT(*) FROM venue_facilities WHERE venue_id IN ({$vIdsStr})")->fetchColumn();
}

$tsIdList = implode(',', $preservedTrainingSessionIds);
$testTrainingSessionCount = (int)$pdo->query("SELECT COUNT(*) FROM training_sessions WHERE id NOT IN ({$tsIdList})")->fetchColumn();
$testTrainingAttendanceCount = (int)$pdo->query("SELECT COUNT(*) FROM training_attendance WHERE training_session_id NOT IN ({$tsIdList})")->fetchColumn();

$invIdList = implode(',', $preservedInventoryItemIds);
$testInventoryCount = (int)$pdo->query("SELECT COUNT(*) FROM inventory_items WHERE id NOT IN ({$invIdList})")->fetchColumn();
$testStockTransCount = (int)$pdo->query("SELECT COUNT(*) FROM stock_transactions WHERE inventory_item_id NOT IN ({$invIdList})")->fetchColumn();

echo "--- INVENTORY OF IDENTIFIED TEST FIXTURES ---\n";
echo "Test Tournaments: {$testTournCount}\n";
echo "  - Matches: {$matchCount}\n";
echo "  - Fixtures: {$fixtureCount}\n";
echo "  - Standings: {$standingsCount}\n";
echo "  - Tournament Teams: {$tournTeamsCount}\n";
echo "  - Tournament Venues: {$tournVenuesCount}\n";
echo "Test Teams: {$testTeamCount}\n";
echo "  - Team Coaches: {$teamCoachesCount}\n";
echo "  - Team Members: {$teamMembersCount}\n";
echo "Test Athletes: {$testAthleteCount}\n";
echo "  - Athlete Guardians: {$guardiansCount}\n";
echo "Test Coach Profiles: {$testCoachProfileCount}\n";
echo "Test Employees: {$testEmployeeCount}\n";
echo "Test Venues: {$testVenueCount}\n";
echo "  - Venue Bookings: {$venueBookingsCount}\n";
echo "  - Venue Facilities: {$venueFacilitiesCount}\n";
echo "Test Training Sessions: {$testTrainingSessionCount}\n";
echo "  - Training Attendance: {$testTrainingAttendanceCount}\n";
echo "Test Inventory Items: {$testInventoryCount}\n";
echo "  - Stock Transactions: {$testStockTransCount}\n";

if ($isDryRun) {
    echo "\n[DRY RUN COMPLETE] No records were modified.\n";
    exit(0);
}

if ($testTournCount === 0 && $testTeamCount === 0 && $testAthleteCount === 0 && $testCoachProfileCount === 0 && $testVenueCount === 0) {
    echo "\n[INFO] Database is already clean. No test fixtures found.\n";
    exit(0);
}

// -------------------------------------------------------------
// 3. EXECUTE CLEANUP IN TRANSACTION
// -------------------------------------------------------------
$pdo->beginTransaction();

try {
    // 1. Remap preserved tournaments (28, 70, 71) so they don't reference deleted test fixtures
    $pdo->exec("UPDATE tournament_teams SET team_id = 1 WHERE tournament_id = 28 AND team_id NOT IN (1, 21)");
    $pdo->exec("UPDATE tournament_standings SET team_id = 1 WHERE tournament_id = 28 AND team_id NOT IN (1, 21)");
    $pdo->exec("UPDATE fixtures SET home_team_id = 1, away_team_id = 21, venue_id = 35 WHERE tournament_id = 28");
    $pdo->exec("UPDATE tournament_venues SET venue_id = 35 WHERE tournament_id = 28 AND venue_id NOT IN (1, 35)");

    $pdo->exec("UPDATE fixtures SET away_team_id = 1 WHERE tournament_id = 70 AND away_team_id NOT IN (1, 21)");
    $pdo->exec("UPDATE tournament_standings SET team_id = 1 WHERE tournament_id = 70 AND team_id NOT IN (1, 21)");

    $pdo->exec("UPDATE fixtures SET away_team_id = 1 WHERE tournament_id = 71 AND away_team_id NOT IN (1, 21)");
    $pdo->exec("UPDATE tournament_standings SET team_id = 1 WHERE tournament_id = 71 AND team_id NOT IN (1, 21)");

    // Remap Team 1 member and Session 1 attendance (athlete 2 -> 23)
    $pdo->exec("UPDATE team_members SET athlete_id = 23 WHERE team_id = 1 AND athlete_id = 2");
    $pdo->exec("UPDATE training_attendance SET athlete_id = 23 WHERE training_session_id = 1 AND athlete_id = 2");

    // 2. Delete test tournament dependents
    if (!empty($testTournIds)) {
        $tIdsStr = implode(',', $testTournIds);
        $pdo->exec("DELETE FROM matches WHERE fixture_id IN (SELECT id FROM fixtures WHERE tournament_id IN ({$tIdsStr}))");
        $pdo->exec("DELETE FROM fixtures WHERE tournament_id IN ({$tIdsStr})");
        $pdo->exec("DELETE FROM tournament_standings WHERE tournament_id IN ({$tIdsStr})");
        $pdo->exec("DELETE FROM tournament_teams WHERE tournament_id IN ({$tIdsStr})");
        $pdo->exec("DELETE FROM tournament_venues WHERE tournament_id IN ({$tIdsStr})");
        $pdo->exec("DELETE FROM tournaments WHERE id IN ({$tIdsStr})");
    }

    // 3. Delete test team dependents
    if (!empty($testTeamIds)) {
        $tmIdsStr = implode(',', $testTeamIds);
        $pdo->exec("DELETE FROM team_coaches WHERE team_id IN ({$tmIdsStr})");
        $pdo->exec("DELETE FROM team_members WHERE team_id IN ({$tmIdsStr})");
        $pdo->exec("DELETE FROM teams WHERE id IN ({$tmIdsStr})");
    }

    // 4. Delete test athletes & guardians
    if (!empty($testAthleteIds)) {
        $aIdsStr = implode(',', $testAthleteIds);
        $pdo->exec("DELETE FROM athlete_guardians WHERE athlete_id IN ({$aIdsStr})");
        $pdo->exec("DELETE FROM athletes WHERE id IN ({$aIdsStr})");
    }

    // 5. Delete test coach profiles & employees
    $pdo->exec("DELETE FROM coach_profiles WHERE id NOT IN ({$cpIdList})");
    $pdo->exec("DELETE FROM employees WHERE id NOT IN ({$empIdList})");

    // 6. Delete test venues, facilities, bookings
    if (!empty($testVenueIds)) {
        $vIdsStr = implode(',', $testVenueIds);
        $pdo->exec("DELETE FROM venue_bookings WHERE venue_id IN ({$vIdsStr})");
        $pdo->exec("DELETE FROM venue_facilities WHERE venue_id IN ({$vIdsStr})");
        $pdo->exec("DELETE FROM venues WHERE id IN ({$vIdsStr})");
    }

    // 7. Delete test training sessions & attendance
    $pdo->exec("DELETE FROM training_attendance WHERE training_session_id NOT IN ({$tsIdList})");
    $pdo->exec("DELETE FROM training_sessions WHERE id NOT IN ({$tsIdList})");

    // 8. Delete test inventory items & stock transactions
    $pdo->exec("DELETE FROM stock_transactions WHERE inventory_item_id NOT IN ({$invIdList})");
    $pdo->exec("DELETE FROM inventory_items WHERE id NOT IN ({$invIdList})");

    // 9. Clean up test audit logs
    $pdo->exec("DELETE FROM audit_logs WHERE table_name = 'tournaments' AND record_id NOT IN ({$tournIdList})");
    $pdo->exec("DELETE FROM audit_logs WHERE table_name = 'teams' AND record_id NOT IN ({$teamIdList})");
    $pdo->exec("DELETE FROM audit_logs WHERE table_name = 'athletes' AND record_id NOT IN ({$athIdList})");
    $pdo->exec("DELETE FROM audit_logs WHERE table_name = 'coach_profiles' AND record_id NOT IN ({$cpIdList})");
    $pdo->exec("DELETE FROM audit_logs WHERE table_name = 'employees' AND record_id NOT IN ({$empIdList})");
    $pdo->exec("DELETE FROM audit_logs WHERE table_name = 'venues' AND record_id NOT IN ({$venueIdList})");
    $pdo->exec("DELETE FROM audit_logs WHERE table_name = 'training_sessions' AND record_id NOT IN ({$tsIdList})");
    $pdo->exec("DELETE FROM audit_logs WHERE table_name = 'inventory_items' AND record_id NOT IN ({$invIdList})");

    $pdo->commit();
    echo "\n[SUCCESS] Cleanup transaction committed safely and successfully.\n";
} catch (\Throwable $e) {
    $pdo->rollBack();
    echo "\n[ERROR] Transaction rolled back: " . $e->getMessage() . "\n";
    exit(1);
}
